package com.bsm.dao;

import com.bsm.entity.TProvince;
import com.bsm.entity.TProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    long countByExample(TProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int deleteByExample(TProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int insert(TProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int insertSelective(TProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    List<TProvince> selectByExampleWithRowbounds(TProvinceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    List<TProvince> selectByExample(TProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    TProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TProvince record, @Param("example") TProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TProvince record, @Param("example") TProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TProvince record);
}