package com.bsm.entity;

import java.io.Serializable;
import java.util.Date;

public class TPlace implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.hottime
     *
     * @mbg.generated
     */
    private Date hottime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.hotticket
     *
     * @mbg.generated
     */
    private Double hotticket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.dimticket
     *
     * @mbg.generated
     */
    private Double dimticket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.provinceid
     *
     * @mbg.generated
     */
    private Integer provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.picpath
     *
     * @mbg.generated
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_place.placedes
     *
     * @mbg.generated
     */
    private String placedes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_place
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.id
     *
     * @return the value of t_place.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.id
     *
     * @param id the value for t_place.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.name
     *
     * @return the value of t_place.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.name
     *
     * @param name the value for t_place.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.hottime
     *
     * @return the value of t_place.hottime
     *
     * @mbg.generated
     */
    public Date getHottime() {
        return hottime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.hottime
     *
     * @param hottime the value for t_place.hottime
     *
     * @mbg.generated
     */
    public void setHottime(Date hottime) {
        this.hottime = hottime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.hotticket
     *
     * @return the value of t_place.hotticket
     *
     * @mbg.generated
     */
    public Double getHotticket() {
        return hotticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.hotticket
     *
     * @param hotticket the value for t_place.hotticket
     *
     * @mbg.generated
     */
    public void setHotticket(Double hotticket) {
        this.hotticket = hotticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.dimticket
     *
     * @return the value of t_place.dimticket
     *
     * @mbg.generated
     */
    public Double getDimticket() {
        return dimticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.dimticket
     *
     * @param dimticket the value for t_place.dimticket
     *
     * @mbg.generated
     */
    public void setDimticket(Double dimticket) {
        this.dimticket = dimticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.provinceid
     *
     * @return the value of t_place.provinceid
     *
     * @mbg.generated
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.provinceid
     *
     * @param provinceid the value for t_place.provinceid
     *
     * @mbg.generated
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.picpath
     *
     * @return the value of t_place.picpath
     *
     * @mbg.generated
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.picpath
     *
     * @param picpath the value for t_place.picpath
     *
     * @mbg.generated
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_place.placedes
     *
     * @return the value of t_place.placedes
     *
     * @mbg.generated
     */
    public String getPlacedes() {
        return placedes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_place.placedes
     *
     * @param placedes the value for t_place.placedes
     *
     * @mbg.generated
     */
    public void setPlacedes(String placedes) {
        this.placedes = placedes == null ? null : placedes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_place
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", hottime=").append(hottime);
        sb.append(", hotticket=").append(hotticket);
        sb.append(", dimticket=").append(dimticket);
        sb.append(", provinceid=").append(provinceid);
        sb.append(", picpath=").append(picpath);
        sb.append(", placedes=").append(placedes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}